In [60]:
import pandas as pd
import numpy as np

In [61]:
df1 = pd.read_csv('before_clean_financial_dataset.csv')

In [62]:
df2 = pd.read_csv('before_clean_fnb_dataset.csv')

In [63]:
df1

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,AGRO,2024,Q324,0.56,478.57,1.92,139.72,-3.264659e+10,0.11,0.40,-1.862482e+11,-7.53,5.0,17.1,2.5
1,AGRO,2024,Q224,0.44,513.64,1.63,138.28,4.654269e+10,0.08,0.32,3.193126e+11,12.91,5.0,17.1,2.5
2,AGRO,2024,Q124,0.37,783.78,2.09,138.52,3.736836e+10,0.07,0.27,-2.206736e+11,-8.92,5.0,17.1,2.5
3,AGRO,2023,Q423,0.39,794.87,2.24,138.25,7.749860e+08,0.08,0.28,5.784586e+11,23.38,4.9,17.5,3.0
4,AGRO,2023,Q323,0.22,1381.82,2.21,137.48,2.462051e+10,0.05,0.16,-4.312402e+11,-17.43,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,SDRA,2016,Q116,9.64,123.34,1.48,805.96,0.000000e+00,0.24,1.20,1.312118e+12,251.78,5.1,21.4,4.0
1478,SDRA,2015,Q415,7.99,136.30,1.37,793.64,0.000000e+00,0.21,1.01,2.212736e+12,424.60,5.2,17.1,4.0
1479,SDRA,2015,Q315,9.30,126.77,1.51,781.05,0.000000e+00,0.25,1.19,5.498790e+11,105.52,5.2,17.1,4.0
1480,SDRA,2015,Q215,14.24,83.15,1.52,777.13,0.000000e+00,0.41,1.83,-1.703234e+12,-326.83,5.2,17.1,4.0
1481,SDRA,2015,Q115,19.36,58.88,1.48,771.51,0.000000e+00,0.56,2.51,-3.046480e+11,-58.46,5.2,17.1,4.0

In [64]:
df2

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,ADES,2024,Q324,196.76,51.20,2.86,3525.89,1.498380e+11,4.69,5.58,-8.470000e+09,-14.36,5.0,17.1,2.5
1,ADES,2024,Q224,173.98,60.78,3.18,3329.13,1.320190e+11,4.45,5.23,3.963500e+10,67.19,5.0,17.1,2.5
2,ADES,2024,Q124,222.76,40.85,2.88,3155.15,1.662250e+11,5.81,7.06,7.798300e+10,132.20,5.0,17.1,2.5
3,ADES,2023,Q423,176.16,54.92,3.30,2932.39,1.398630e+11,4.98,6.01,1.156430e+11,196.04,4.9,17.5,3.0
4,ADES,2023,Q323,180.55,58.85,3.85,2757.63,1.372790e+11,5.49,6.55,1.074140e+11,182.09,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,UNVR,2016,Q116,205.77,208.61,51.20,838.45,0.000000e+00,9.43,24.54,1.053940e+12,138.13,5.1,21.4,4.0
815,UNVR,2015,Q415,218.69,169.19,58.48,632.68,0.000000e+00,10.61,34.57,2.200957e+12,288.46,5.2,17.1,4.0
816,UNVR,2015,Q315,164.16,231.48,49.88,761.78,0.000000e+00,7.84,21.55,6.868200e+11,90.02,5.2,17.1,4.0
817,UNVR,2015,Q215,175.48,225.10,66.10,597.62,0.000000e+00,8.12,29.36,1.151308e+12,150.89,5.2,17.1,4.0
818,UNVR,2015,Q115,208.61,190.07,47.31,838.14,0.000000e+00,10.77,24.89,7.875220e+11,103.21,5.2,17.1,4.0

In [65]:
df1 = df1[df1['emiten_code']!='MCOR'].reset_index(drop=True)

In [66]:
df1

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,AGRO,2024,Q324,0.56,478.57,1.92,139.72,-3.264659e+10,0.11,0.40,-1.862482e+11,-7.53,5.0,17.1,2.5
1,AGRO,2024,Q224,0.44,513.64,1.63,138.28,4.654269e+10,0.08,0.32,3.193126e+11,12.91,5.0,17.1,2.5
2,AGRO,2024,Q124,0.37,783.78,2.09,138.52,3.736836e+10,0.07,0.27,-2.206736e+11,-8.92,5.0,17.1,2.5
3,AGRO,2023,Q423,0.39,794.87,2.24,138.25,7.749860e+08,0.08,0.28,5.784586e+11,23.38,4.9,17.5,3.0
4,AGRO,2023,Q323,0.22,1381.82,2.21,137.48,2.462051e+10,0.05,0.16,-4.312402e+11,-17.43,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,SDRA,2016,Q116,9.64,123.34,1.48,805.96,0.000000e+00,0.24,1.20,1.312118e+12,251.78,5.1,21.4,4.0
1439,SDRA,2015,Q415,7.99,136.30,1.37,793.64,0.000000e+00,0.21,1.01,2.212736e+12,424.60,5.2,17.1,4.0
1440,SDRA,2015,Q315,9.30,126.77,1.51,781.05,0.000000e+00,0.25,1.19,5.498790e+11,105.52,5.2,17.1,4.0
1441,SDRA,2015,Q215,14.24,83.15,1.52,777.13,0.000000e+00,0.41,1.83,-1.703234e+12,-326.83,5.2,17.1,4.0
1442,SDRA,2015,Q115,19.36,58.88,1.48,771.51,0.000000e+00,0.56,2.51,-3.046480e+11,-58.46,5.2,17.1,4.0

In [67]:
df3 = pd.read_excel('filtered_quarterly_open.xlsx')

In [68]:
df3

            Date     Open source_file     return
0     2025-01-01   232.00        AGRO        NaN
1     2024-10-01   270.00        AGRO  19.469027
2     2024-07-01   226.00        AGRO -22.602740
3     2024-04-01   292.00        AGRO  -5.806452
4     2024-01-01   310.00        AGRO   1.973684
...          ...      ...         ...        ...
1511  2016-01-01  1038.65        SDRA  -7.562988
1512  2015-10-01  1123.63        SDRA  -0.418310
1513  2015-07-01  1128.35        SDRA   3.913027
1514  2015-04-01  1085.86        SDRA   0.000000
1515  2015-01-01  1085.86        SDRA        NaN

[1516 rows x 4 columns]

In [69]:
df3 = df3.drop(columns=['Date', 'Open', 'source_file',])

In [70]:
df3.columns

Index(['return'], dtype='object')

In [71]:
df3 = df3.dropna(subset=['return']).reset_index(drop=True)

In [72]:
df3

         return
0     19.469027
1    -22.602740
2     -5.806452
3      1.973684
4    -20.833333
...         ...
1438   9.090647
1439  -7.562988
1440  -0.418310
1441   3.913027
1442   0.000000

[1443 rows x 1 columns]

In [73]:
df1

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,AGRO,2024,Q324,0.56,478.57,1.92,139.72,-3.264659e+10,0.11,0.40,-1.862482e+11,-7.53,5.0,17.1,2.5
1,AGRO,2024,Q224,0.44,513.64,1.63,138.28,4.654269e+10,0.08,0.32,3.193126e+11,12.91,5.0,17.1,2.5
2,AGRO,2024,Q124,0.37,783.78,2.09,138.52,3.736836e+10,0.07,0.27,-2.206736e+11,-8.92,5.0,17.1,2.5
3,AGRO,2023,Q423,0.39,794.87,2.24,138.25,7.749860e+08,0.08,0.28,5.784586e+11,23.38,4.9,17.5,3.0
4,AGRO,2023,Q323,0.22,1381.82,2.21,137.48,2.462051e+10,0.05,0.16,-4.312402e+11,-17.43,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,SDRA,2016,Q116,9.64,123.34,1.48,805.96,0.000000e+00,0.24,1.20,1.312118e+12,251.78,5.1,21.4,4.0
1439,SDRA,2015,Q415,7.99,136.30,1.37,793.64,0.000000e+00,0.21,1.01,2.212736e+12,424.60,5.2,17.1,4.0
1440,SDRA,2015,Q315,9.30,126.77,1.51,781.05,0.000000e+00,0.25,1.19,5.498790e+11,105.52,5.2,17.1,4.0
1441,SDRA,2015,Q215,14.24,83.15,1.52,777.13,0.000000e+00,0.41,1.83,-1.703234e+12,-326.83,5.2,17.1,4.0
1442,SDRA,2015,Q115,19.36,58.88,1.48,771.51,0.000000e+00,0.56,2.51,-3.046480e+11,-58.46,5.2,17.1,4.0

In [74]:
df3

         return
0     19.469027
1    -22.602740
2     -5.806452
3      1.973684
4    -20.833333
...         ...
1438   9.090647
1439  -7.562988
1440  -0.418310
1441   3.913027
1442   0.000000

[1443 rows x 1 columns]

In [75]:
df1['date'] = df1['date'].str[:-2]

In [76]:
df1 = pd.concat([df1, df3], axis=1)

In [77]:
df1

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast,return
0,AGRO,2024,Q3,0.56,478.57,1.92,139.72,-3.264659e+10,0.11,0.40,-1.862482e+11,-7.53,5.0,17.1,2.5,19.469027
1,AGRO,2024,Q2,0.44,513.64,1.63,138.28,4.654269e+10,0.08,0.32,3.193126e+11,12.91,5.0,17.1,2.5,-22.602740
2,AGRO,2024,Q1,0.37,783.78,2.09,138.52,3.736836e+10,0.07,0.27,-2.206736e+11,-8.92,5.0,17.1,2.5,-5.806452
3,AGRO,2023,Q4,0.39,794.87,2.24,138.25,7.749860e+08,0.08,0.28,5.784586e+11,23.38,4.9,17.5,3.0,1.973684
4,AGRO,2023,Q3,0.22,1381.82,2.21,137.48,2.462051e+10,0.05,0.16,-4.312402e+11,-17.43,4.9,17.5,3.0,-20.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,SDRA,2016,Q1,9.64,123.34,1.48,805.96,0.000000e+00,0.24,1.20,1.312118e+12,251.78,5.1,21.4,4.0,9.090647
1439,SDRA,2015,Q4,7.99,136.30,1.37,793.64,0.000000e+00,0.21,1.01,2.212736e+12,424.60,5.2,17.1,4.0,-7.562988
1440,SDRA,2015,Q3,9.30,126.77,1.51,781.05,0.000000e+00,0.25,1.19,5.498790e+11,105.52,5.2,17.1,4.0,-0.418310
1441,SDRA,2015,Q2,14.24,83.15,1.52,777.13,0.000000e+00,0.41,1.83,-1.703234e+12,-326.83,5.2,17.1,4.0,3.913027
1442,SDRA,2015,Q1,19.36,58.88,1.48,771.51,0.000000e+00,0.56,2.51,-3.046480e+11,-58.46,5.2,17.1,4.0,0.000000

In [78]:
df1 = df1.apply(lambda col: col.fillna(col.min()), axis=0)

In [79]:
df1.isna().sum()

emiten_code            0
year                   0
date                   0
eps                    0
per                    0
pbv                    0
bvps                   0
ebitda                 0
roa                    0
roe                    0
fcf                    0
fcf_ps                 0
gdp_forecast           0
political_stability    0
inflation_forecast     0
return                 0
dtype: int64

In [80]:
df1.to_csv('clean_financial_data.csv', index=False)

In [81]:
df2 = df2.apply(lambda col: col.fillna(col.min()), axis=0)

In [82]:
df2.isna().sum()

emiten_code            0
year                   0
date                   0
eps                    0
per                    0
pbv                    0
bvps                   0
ebitda                 0
roa                    0
roe                    0
fcf                    0
fcf_ps                 0
gdp_forecast           0
political_stability    0
inflation_forecast     0
dtype: int64

In [83]:
df4 = pd.read_excel('filtered_quarterly_open_fnb.xlsx')

In [84]:
df4 = df4.drop(columns=['Date', 'Open', 'source_file'])

In [85]:
df4 = df4.dropna(subset=['return']).reset_index(drop=True)

In [86]:
df2['date'] = df2['date'].str[:-2]

In [87]:
df2

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,ADES,2024,Q3,196.76,51.20,2.86,3525.89,1.498380e+11,4.69,5.58,-8.470000e+09,-14.36,5.0,17.1,2.5
1,ADES,2024,Q2,173.98,60.78,3.18,3329.13,1.320190e+11,4.45,5.23,3.963500e+10,67.19,5.0,17.1,2.5
2,ADES,2024,Q1,222.76,40.85,2.88,3155.15,1.662250e+11,5.81,7.06,7.798300e+10,132.20,5.0,17.1,2.5
3,ADES,2023,Q4,176.16,54.92,3.30,2932.39,1.398630e+11,4.98,6.01,1.156430e+11,196.04,4.9,17.5,3.0
4,ADES,2023,Q3,180.55,58.85,3.85,2757.63,1.372790e+11,5.49,6.55,1.074140e+11,182.09,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,UNVR,2016,Q1,205.77,208.61,51.20,838.45,0.000000e+00,9.43,24.54,1.053940e+12,138.13,5.1,21.4,4.0
815,UNVR,2015,Q4,218.69,169.19,58.48,632.68,0.000000e+00,10.61,34.57,2.200957e+12,288.46,5.2,17.1,4.0
816,UNVR,2015,Q3,164.16,231.48,49.88,761.78,0.000000e+00,7.84,21.55,6.868200e+11,90.02,5.2,17.1,4.0
817,UNVR,2015,Q2,175.48,225.10,66.10,597.62,0.000000e+00,8.12,29.36,1.151308e+12,150.89,5.2,17.1,4.0
818,UNVR,2015,Q1,208.61,190.07,47.31,838.14,0.000000e+00,10.77,24.89,7.875220e+11,103.21,5.2,17.1,4.0

In [88]:
df2 = pd.concat([df2,df4], axis=1)

In [89]:
df2

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast,return
0,ADES,2024,Q3,196.76,51.20,2.86,3525.89,1.498380e+11,4.69,5.58,-8.470000e+09,-14.36,5.0,17.1,2.5,-5.687204
1,ADES,2024,Q2,173.98,60.78,3.18,3329.13,1.320190e+11,4.45,5.23,3.963500e+10,67.19,5.0,17.1,2.5,15.300546
2,ADES,2024,Q1,222.76,40.85,2.88,3155.15,1.662250e+11,5.81,7.06,7.798300e+10,132.20,5.0,17.1,2.5,-5.426357
3,ADES,2023,Q4,176.16,54.92,3.30,2932.39,1.398630e+11,4.98,6.01,1.156430e+11,196.04,4.9,17.5,3.0,-7.857143
4,ADES,2023,Q3,180.55,58.85,3.85,2757.63,1.372790e+11,5.49,6.55,1.074140e+11,182.09,4.9,17.5,3.0,24.629080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,UNVR,2016,Q1,205.77,208.61,51.20,838.45,0.000000e+00,9.43,24.54,1.053940e+12,138.13,5.1,21.4,4.0,16.216216
815,UNVR,2015,Q4,218.69,169.19,58.48,632.68,0.000000e+00,10.61,34.57,2.200957e+12,288.46,5.2,17.1,4.0,-2.631579
816,UNVR,2015,Q3,164.16,231.48,49.88,761.78,0.000000e+00,7.84,21.55,6.868200e+11,90.02,5.2,17.1,4.0,-4.761905
817,UNVR,2015,Q2,175.48,225.10,66.10,597.62,0.000000e+00,8.12,29.36,1.151308e+12,150.89,5.2,17.1,4.0,1.785714
818,UNVR,2015,Q1,208.61,190.07,47.31,838.14,0.000000e+00,10.77,24.89,7.875220e+11,103.21,5.2,17.1,4.0,21.362229

In [90]:
df2.to_csv('clean_fnb_data.csv', index=False)