In [57]:
import pandas as pd
import numpy as np

In [58]:
df2 = pd.read_csv('financial_data_2_income statement.csv')

In [59]:
df2.head(20)

,Unnamed: 0,Q324,Q224,Q124,Q423,Q323,Q223,Q123,Q422,Q322,...,Q309,Q209,Q109,Q408,Q308,Q208,Q108,Q424,Q407,Q406
0,NaN,6.134717e+09,6.134717e+09,6.134717e+09,6.134717e+09,6.134717e+09,6.134717e+09,6.134717e+09,5.937094e+09,5.937094e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,6.740000e+00,5.880000e+00,5.350000e+00,6.090000e+00,8.990000e+00,9.210000e+00,9.590000e+00,1.048000e+01,7.060000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,6.201800e+02,7.125900e+02,7.850500e+02,6.715900e+02,4.282500e+02,4.310500e+02,4.191900e+02,3.807300e+02,5.481600e+02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,5.742000e+01,5.403000e+01,5.154000e+01,5.373000e+01,5.305000e+01,5.811000e+01,6.238000e+01,6.739000e+01,7.136000e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,6.599000e+10,5.809900e+10,5.622900e+10,1.065880e+11,8.123700e+10,8.367100e+10,8.244300e+10,9.407700e+10,6.040700e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,1.800000e-01,1.500000e-01,1.200000e-01,1.500000e-01,2.300000e-01,2.500000e-01,2.700000e-01,3.000000e-01,2.100000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,1.130000e+00,1.000000e+00,9.200000e-01,1.050000e+00,1.570000e+00,1.630000e+00,1.750000e+00,1.890000e+00,1.750000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,2.300000e-01,1.800000e-01,1.700000e-01,1.900000e-01,3.100000e-01,3.400000e-01,3.600000e-01,3.800000e-01,2.900000e-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,1.052144e+10,...,6.164402e+09,6.164402e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,4.155000e+01,3.437000e+01,3.462000e+01,3.265000e+01,4.892000e+01,5.213000e+01,3.532000e+01,4.477000e+01,5.727000e+01,...,3.048000e+01,6.469000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,2.323000e+01,2.822000e+01,3.495000e+01,3.522000e+01,2.392000e+01,2.264000e+01,3.851000e+01,3.004000e+01,2.366000e+01,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,2.630000e+00,2.610000e+00,3.310000e+00,3.230000e+00,3.430000e+00,3.560000e+00,4.180000e+00,3.770000e+00,4.240000e+00,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,5.199380e+11,5.718990e+11,7.295820e+11,4.405930e+11,7.388950e+11,7.619160e+11,5.409000e+11,6.576230e+11,8.173110e+11,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,2.100000e-01,1.700000e-01,1.800000e-01,1.800000e-01,2.900000e-01,3.100000e-01,2.100000e-01,2.600000e-01,3.500000e-01,...,5.800000e-01,1.320000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,2.720000e+00,2.380000e+00,2.280000e+00,2.210000e+00,3.420000e+00,3.680000e+00,2.440000e+00,3.190000e+00,4.320000e+00,...,6.720000e+00,1.531000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,2.500000e-01,2.400000e-01,2.400000e-01,2.200000e-01,3.500000e-01,3.700000e-01,2.500000e-01,3.500000e-01,4.300000e-01,...,8.200000e-01,3.600000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,1.501550e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,2.059000e+01,2.071000e+01,2.063000e+01,2.500000e+01,2.495000e+01,2.763000e+01,2.033000e+01,2.261000e+01,2.584000e+01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
col_index = df2.columns.get_loc('Q115') + 1
df2 = df2.iloc[:, :col_index]

In [61]:
df2.drop('Unnamed: 0', axis=1, inplace=True)

In [62]:
# 🔹 Daftar fitur (9 fitur per kuartal)
features = [
    "share_outstanding", "eps", "per", "price_to_sales", "ebitda",
    "roa", "roe", "roce", "interest_coverage"
]

# 🔹 Daftar kode emiten
emiten_code = [
    "BINA", "BJBR", "BJTM", "BKSW", "BMAS", "BMRI", "BNBA", "BNGA",
    "BNII", "BNLI", "BSIM", "BSWD", "BTPN", "BVIC", "DNAR", "INPC",
    "MAYA", "AGRO", "AGRS", "BABP", "BACA", "BBCA", "BBKP", "BBMD",
    "BBNI", "BBRI", "BBTN", "BBYB", "BCIC", "BDMN", "BEKS", "MCOR",
    "MEGA", "NISP", "NOBU", "PNBN", "PNBS", "SDRA"
]

result = []
num_emitens = len(emiten_code)  # Jumlah kode emiten
num_rows_per_emiten = len(df2) // (9 * num_emitens)  # Banyaknya data per emiten

for col in df2.columns:
    for i in range(num_emitens):
        for start in range(i * 9 * num_rows_per_emiten, (i + 1) * 9 * num_rows_per_emiten, 9):
            if start + 9 <= len(df2):
                row = {feature: df2[col].iloc[start + j] for j, feature in enumerate(features)}
                row['date'] = col
                row['emiten_code'] = emiten_code[i]  # Tambahkan kode emiten
                result.append(row)

# 🔹 Mengubah hasil menjadi DataFrame baru
final_df2 = pd.DataFrame(result)

# 🔹 Tampilkan hasil akhir
print(final_df2)

      share_outstanding    eps      per  price_to_sales        ebitda   roa  \
0          6.134717e+09   6.74   620.18           57.42  6.599000e+10  0.18
1          1.052144e+10  41.55    23.23            2.63  5.199380e+11  0.21
2          1.501550e+10  20.59    27.68            4.27  5.099790e+11  0.29
3          3.515805e+10   0.49   124.49           11.40  4.510100e+10  0.14
4          1.810266e+10   0.28  2875.00           37.28  1.463565e+10  0.02
...                 ...    ...      ...             ...           ...   ...
1477       1.147265e+10  32.45    43.14            7.41  0.000000e+00  0.32
1478       4.311330e+09   0.75  1086.67           30.03  0.000000e+00  0.05
1479       2.408765e+10  24.41    58.38            8.43  0.000000e+00  0.35
1480       9.840314e+09   1.88   123.94           13.74  0.000000e+00  0.29
1481       5.211339e+09  19.36    58.88           16.36  0.000000e+00  0.56

       roe  roce  interest_coverage  date emiten_code
0     1.13  0.23                0.0  Q324        BINA
1     2.72  0.25                0.0  Q324        BJBR
2     2.50  0.43                0.0  Q324        BJTM
3     0.36  0.24                0.0  Q324        BKSW
4     0.08  0.04                0.0  Q324        BMAS
...    ...   ...                ...   ...         ...
1477  2.43  0.45                0.0  Q115        NISP
1478  0.27  0.08                0.0  Q115        NOBU
1479  2.72  0.50                0.0  Q115        PNBN
1480  1.69  0.39                0.0  Q115        PNBS
1481  2.51  0.65                0.0  Q115        SDRA

[1482 rows x 11 columns]

In [63]:
final_df2

,share_outstanding,eps,per,price_to_sales,ebitda,roa,roe,roce,interest_coverage,date,emiten_code
0,6.134717e+09,6.74,620.18,57.42,6.599000e+10,0.18,1.13,0.23,0.0,Q324,BINA
1,1.052144e+10,41.55,23.23,2.63,5.199380e+11,0.21,2.72,0.25,0.0,Q324,BJBR
2,1.501550e+10,20.59,27.68,4.27,5.099790e+11,0.29,2.50,0.43,0.0,Q324,BJTM
3,3.515805e+10,0.49,124.49,11.40,4.510100e+10,0.14,0.36,0.24,0.0,Q324,BKSW
4,1.810266e+10,0.28,2875.00,37.28,1.463565e+10,0.02,0.08,0.04,0.0,Q324,BMAS
...,...,...,...,...,...,...,...,...,...,...,...
1477,1.147265e+10,32.45,43.14,7.41,0.000000e+00,0.32,2.43,0.45,0.0,Q115,NISP
1478,4.311330e+09,0.75,1086.67,30.03,0.000000e+00,0.05,0.27,0.08,0.0,Q115,NOBU
1479,2.408765e+10,24.41,58.38,8.43,0.000000e+00,0.35,2.72,0.50,0.0,Q115,PNBN
1480,9.840314e+09,1.88,123.94,13.74,0.000000e+00,0.29,1.69,0.39,0.0,Q115,PNBS
1481,5.211339e+09,19.36,58.88,16.36,0.000000e+00,0.56,2.51,0.65,0.0,Q115,SDRA

In [64]:
final_df2 = final_df2.drop(columns=['share_outstanding','price_to_sales','roce','interest_coverage'])

In [65]:
df3 = pd.read_csv('fnb_data_2_income statement.csv')

In [66]:
col_index = df3.columns.get_loc('Q115') + 1
df3 = df3.iloc[:, :col_index]

In [67]:
df3.drop('Unnamed: 0', axis=1, inplace=True)

In [68]:
df3

,Q324,Q224,Q124,Q423,Q323,Q223,Q123,Q422,Q322,Q222,...,Q217,Q117,Q416,Q316,Q216,Q116,Q415,Q315,Q215,Q115
0,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,...,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08,5.898968e+08
1,1.967600e+02,1.739800e+02,2.227600e+02,1.761600e+02,1.805500e+02,1.626400e+02,1.516100e+02,2.107300e+02,1.419400e+02,1.378900e+02,...,3.200000e+00,1.891000e+01,4.091000e+01,1.604000e+01,1.232000e+01,2.557000e+01,2.683000e+01,-2.600000e+00,1.078000e+01,2.066000e+01
2,5.120000e+01,6.078000e+01,4.085000e+01,5.492000e+01,5.885000e+01,5.211000e+01,4.864000e+01,3.405000e+01,5.055000e+01,4.841000e+01,...,3.375000e+02,6.187000e+01,2.444000e+01,8.105000e+01,1.047100e+02,4.106000e+01,3.783000e+01,-4.076900e+02,1.294100e+02,6.655000e+01
3,1.267000e+01,1.545000e+01,1.158000e+01,1.328000e+01,1.720000e+01,1.410000e+01,1.155000e+01,1.154000e+01,1.319000e+01,1.274000e+01,...,3.050000e+00,3.510000e+00,2.570000e+00,3.690000e+00,3.080000e+00,3.050000e+00,3.150000e+00,4.000000e+00,5.060000e+00,5.060000e+00
4,1.498380e+11,1.320190e+11,1.662250e+11,1.398630e+11,1.372790e+11,1.280820e+11,1.240000e+11,1.887580e+11,1.003900e+11,9.925100e+10,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,9.078240e+11,1.524085e+12,2.148313e+12,1.066475e+12,2.539448e+12,2.008030e+12,2.095313e+12,1.307097e+12,1.799220e+12,2.147014e+12,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
185,3.280000e+00,5.160000e+00,7.900000e+00,3.670000e+00,7.550000e+00,6.790000e+00,7.190000e+00,4.110000e+00,5.840000e+00,6.360000e+00,...,8.620000e+00,1.055000e+01,9.790000e+00,8.670000e+00,9.130000e+00,9.430000e+00,1.061000e+01,7.840000e+00,8.120000e+00,1.077000e+01
186,1.580000e+01,3.565000e+01,2.991000e+01,1.810000e+01,2.657000e+01,3.440000e+01,2.630000e+01,1.884000e+01,2.062000e+01,3.085000e+01,...,3.390000e+01,2.942000e+01,3.486000e+01,2.290000e+01,3.534000e+01,2.454000e+01,3.457000e+01,2.155000e+01,2.936000e+01,2.489000e+01
187,1.377000e+01,2.183000e+01,3.039000e+01,1.292000e+01,2.775000e+01,2.684000e+01,2.815000e+01,1.524000e+01,2.099000e+01,2.393000e+01,...,3.191000e+01,3.860000e+01,3.420000e+01,3.090000e+01,3.600000e+01,3.353000e+01,3.754000e+01,2.870000e+01,3.005000e+01,3.354000e+01
188,2.298000e+01,1.453800e+02,7.615000e+01,3.102000e+01,1.104000e+02,8.372000e+01,4.453000e+01,4.018000e+01,1.056600e+02,1.598800e+02,...,1.389300e+02,6.449000e+01,8.823000e+01,3.944000e+01,9.326000e+01,5.076000e+01,3.901000e+01,6.020000e+01,2.968390e+03,6.349000e+01

In [69]:
# 🔹 Daftar fitur (9 fitur per kuartal)
features = [
    "share_outstanding", "eps", "per", "price_to_sales", "ebitda",
    "roa", "roe", "roce", "interest_coverage"
]

# 🔹 Daftar kode emiten (38 emiten)
emiten_code = [
    "ADES", "AISA", "ALTO", "BTEK", "BUDI", "CEKA", "DLTA", "ICBP",
        "IIKP", "INDF", "MGNA", "MLBI", "MYOR", "PSDN", "ROTI", "SKBM",
        "SKLT", "STTP", "TBLA", "ULTJ", "UNVR"
]

result = []
num_emitens = len(emiten_code)  # 38 emiten

for col in df3.columns:  # Loop setiap kuartal (Q324, Q224, ...)
    for i, emiten in enumerate(emiten_code):
        start = i * 9  # Indeks awal untuk setiap emiten (9 baris per emiten)
        if start + 9 <= len(df3):  # Pastikan tidak keluar dari batas
            row = {feature: df3[col].iloc[start + j] for j, feature in enumerate(features)}
            row['date'] = col
            row['emiten_code'] = emiten  # Tambahkan kode emiten
            result.append(row)

# 🔹 Mengubah hasil menjadi DataFrame baru
final_df3 = pd.DataFrame(result)

# 🔹 Tampilkan hasil akhir
print(final_df3)

     share_outstanding     eps     per  price_to_sales        ebitda    roa  \
0         5.898968e+08  196.76   51.20           12.67  1.498380e+11   4.69
1         9.311800e+09    1.98   66.16            2.41  5.519000e+10   0.95
2         2.191871e+09   -6.72   -2.38            2.37 -1.701817e+10  -1.58
3         4.627750e+10    0.22   18.18            0.76  8.404274e+09   0.25
4         4.498997e+09    4.33   53.58            0.93  7.719400e+10   0.53
..                 ...     ...     ...             ...           ...    ...
814       6.907405e+08    5.67   56.44            1.20  0.000000e+00   1.15
815       1.310000e+09   39.55   77.24            6.40  0.000000e+00   2.91
816       4.942099e+09   18.39   35.07            2.37  0.000000e+00   1.21
817       2.888382e+09   51.50   77.13           11.08  0.000000e+00   4.72
818       7.630000e+09  208.61  190.07           32.14  0.000000e+00  10.77

       roe   roce  interest_coverage  date emiten_code
0     5.58   6.52            5892.43  Q324        ADES
1     1.79   2.77               4.89  Q324        AISA
2    -4.94  -2.64             -18.01  Q324        ALTO
3     0.93  -0.02              -5.22  Q324        BTEK
4     1.30   1.78               0.95  Q324        BUDI
..     ...    ...                ...   ...         ...
814   2.49   3.16               3.45  Q115        SKLT
815   6.06   7.08               5.20  Q115        STTP
816   3.58   4.05               4.12  Q115        TBLA
817   6.19   7.39            1214.74  Q115        ULTJ
818  24.89  33.54              63.49  Q115        UNVR

[819 rows x 11 columns]

In [70]:
final_df3 = final_df3.drop(columns=['share_outstanding','price_to_sales','roce','interest_coverage'])

In [71]:
df4 = pd.read_csv('financial_data_bs_kr.csv')

In [72]:
df4

,Unnamed: 0,Q324,Q224,Q124,Q423,Q323,Q223,Q123,Q422,Q322,...,Q309,Q209,Q109,Q408,Q308,Q208,Q108,Q424,Q407,Q406
0,NaN,6.990000e+00,7.160000e+00,7.230000e+00,7.060000e+00,6.740000e+00,7.010000e+00,7.310000e+00,7.200000e+00,9.580000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,5.981000e+02,5.852000e+02,5.812300e+02,5.796800e+02,5.712200e+02,5.663600e+02,5.496000e+02,5.538200e+02,4.040000e+02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,6.990000e+00,7.160000e+00,7.230000e+00,7.060000e+00,6.740000e+00,7.010000e+00,7.310000e+00,7.200000e+00,9.580000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,5.981000e+02,5.852000e+02,5.812300e+02,5.796800e+02,5.712200e+02,5.663600e+02,5.496000e+02,5.538200e+02,4.040000e+02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN
376,NaN,1.372614e+13,1.358724e+13,1.059066e+13,1.027308e+13,1.026537e+13,1.012870e+13,9.937727e+12,9.930753e+12,9.672374e+12,...,2.195618e+11,1.997138e+11,2.039543e+11,2.005261e+11,1.931031e+11,NaN,1.777120e+11,NaN,1.798096e+11,NaN
377,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN
378,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN
379,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,NaN

In [73]:
col_index = df4.columns.get_loc('Q115') + 1
df4 = df4.iloc[:, :col_index]
df4.drop('Unnamed: 0', axis=1, inplace=True)

In [74]:
features = [
    'pbv','bvps','ptbv','tbvps','std','ltd',
    'total_equity','total_debt','net_debt',
    'working_capital'
]

result = []
for col in df4.columns:
    for start in range(0, len(df4), 10):
        if start + 10 <= len(df4):
            row = {feature: df4[col].iloc[start + i] for i, feature in enumerate(features)}
            row['date'] = col
            result.append(row)

# Mengubah hasil menjadi DataFrame baru
final_df4 = pd.DataFrame(result)

print(final_df4)

       pbv     bvps  ptbv    tbvps  std  ltd  total_equity  total_debt  \
0     6.99   598.10  6.99   598.10  0.0  0.0  3.669194e+12         0.0
1     0.63  1528.97  0.63  1527.85  0.0  0.0  1.608701e+13         0.0
2     0.69   822.24  0.69   822.24  0.0  0.0  1.234631e+13         0.0
3     0.45   135.40  0.46   133.78  0.0  0.0  4.760305e+12         0.0
4     2.15   374.51  2.15   374.24  0.0  0.0  6.779585e+12         0.0
...    ...      ...   ...      ...  ...  ...           ...         ...
1477  1.05  1336.26  1.05  1336.26  0.0  0.0  1.533046e+13         0.0
1478  2.96   274.88  2.97   274.69  0.0  0.0  1.185113e+12         0.0
1479  1.59   896.42  1.59   896.01  0.0  0.0  2.159273e+13         0.0
1480  2.10   111.07  2.10   110.77  0.0  0.0  1.092983e+12         0.0
1481  1.48   771.51  2.63   432.67  0.0  0.0  4.020575e+12         0.0

      net_debt  working_capital  date
0          0.0              0.0  Q324
1          0.0              0.0  Q324
2          0.0              0.0  Q324
3          0.0              0.0  Q324
4          0.0              0.0  Q324
...        ...              ...   ...
1477       0.0              0.0  Q115
1478       0.0              0.0  Q115
1479       0.0              0.0  Q115
1480       0.0              0.0  Q115
1481       0.0              0.0  Q115

[1482 rows x 11 columns]

In [75]:
final_df4 = final_df4.drop(columns=['ptbv','tbvps','std','ltd',
    'total_equity','total_debt','net_debt',
    'working_capital','date'])

In [76]:
df5 = pd.read_csv('fnb_data_bs_kr.csv')

In [77]:
col_index = df5.columns.get_loc('Q115') + 1
df5 = df5.iloc[:, :col_index]
df5.drop('Unnamed: 0', axis=1, inplace=True)

In [78]:
features = [
    'pbv','bvps','ptbv','tbvps','std','ltd',
    'total_equity','total_debt','net_debt',
    'working_capital'
]

result = []
for col in df5.columns:
    for start in range(0, len(df5), 10):
        if start + 10 <= len(df5):
            row = {feature: df5[col].iloc[start + i] for i, feature in enumerate(features)}
            row['date'] = col
            result.append(row)

# Mengubah hasil menjadi DataFrame baru
final_df5 = pd.DataFrame(result)

print(final_df5)

       pbv     bvps   ptbv    tbvps           std           ltd  total_equity  \
0     2.86  3525.89   2.86  3525.88  1.550000e+08  3.700000e+07  2.079909e+12
1     1.18   110.77   1.52    85.96  1.251970e+11  2.216990e+11  1.031492e+12
2     0.12   136.07   0.12   136.07  0.000000e+00  4.584436e+11  2.982412e+11
3     0.17    23.56  30.77     0.13  8.293487e+10  2.114425e+12  1.090408e+12
4     0.70   333.41   0.70   333.41  1.198972e+12  1.287380e+11  1.500023e+12
..     ...      ...    ...      ...           ...           ...           ...
814   1.41   227.58   1.41   227.58  6.029438e+10  3.340339e+10  1.571959e+11
815   4.69   652.08   4.69   652.08  3.407033e+11  2.874861e+11  8.542274e+11
816   1.26   513.49   1.26   513.49  1.354461e+12  1.961982e+12  2.537697e+12
817   4.77   832.15   4.80   827.91  1.898927e+09  0.000000e+00  2.403565e+12
818  47.31   838.14  51.40   771.44  1.000000e+11  0.000000e+00  6.394982e+12

       total_debt      net_debt  working_capital  date
0    1.920000e+08 -7.285450e+11     1.035843e+12  Q324
1    3.468960e+11  1.878420e+11     4.211000e+10  Q324
2    4.584436e+11  4.568268e+11    -5.262894e+10  Q324
3    2.197360e+12  2.125077e+12    -4.000896e+11  Q324
4    1.327710e+12  1.240579e+12     4.733380e+11  Q324
..            ...           ...              ...   ...
814  9.369777e+10  8.393277e+10     2.602342e+10  Q115
815  6.281895e+11  6.141773e+11     2.494106e+11  Q115
816  3.316443e+12  2.924995e+12     4.637520e+11  Q115
817  1.898927e+09 -5.971730e+11     1.249212e+12  Q115
818  1.000000e+11 -3.632780e+11    -9.797290e+11  Q115

[819 rows x 11 columns]

In [79]:
final_df5 = final_df5.drop(columns=['ptbv','tbvps','std','ltd',
    'total_equity','total_debt','net_debt',
    'working_capital','date'])

In [80]:
final_df2

        eps      per        ebitda   roa   roe  date emiten_code
0      6.74   620.18  6.599000e+10  0.18  1.13  Q324        BINA
1     41.55    23.23  5.199380e+11  0.21  2.72  Q324        BJBR
2     20.59    27.68  5.099790e+11  0.29  2.50  Q324        BJTM
3      0.49   124.49  4.510100e+10  0.14  0.36  Q324        BKSW
4      0.28  2875.00  1.463565e+10  0.02  0.08  Q324        BMAS
...     ...      ...           ...   ...   ...   ...         ...
1477  32.45    43.14  0.000000e+00  0.32  2.43  Q115        NISP
1478   0.75  1086.67  0.000000e+00  0.05  0.27  Q115        NOBU
1479  24.41    58.38  0.000000e+00  0.35  2.72  Q115        PNBN
1480   1.88   123.94  0.000000e+00  0.29  1.69  Q115        PNBS
1481  19.36    58.88  0.000000e+00  0.56  2.51  Q115        SDRA

[1482 rows x 7 columns]

In [81]:
final_df4

       pbv     bvps
0     6.99   598.10
1     0.63  1528.97
2     0.69   822.24
3     0.45   135.40
4     2.15   374.51
...    ...      ...
1477  1.05  1336.26
1478  2.96   274.88
1479  1.59   896.42
1480  2.10   111.07
1481  1.48   771.51

[1482 rows x 2 columns]

In [82]:
df6 = pd.read_csv('financial_data_cash flow.csv')

In [83]:
col_index = df6.columns.get_loc('Q115') + 1
df6 = df6.iloc[:, :col_index]
df6.drop('Unnamed: 0', axis=1, inplace=True)

In [84]:
features = [
    'ocf','capex','fcf','fcf_ps'
]

result = []
for col in df6.columns:
    for start in range(0, len(df6), 4):
        if start + 4 <= len(df6):
            row = {feature: df6[col].iloc[start + i] for i, feature in enumerate(features)}
            row['date'] = col
            result.append(row)

# Mengubah hasil menjadi DataFrame baru
final_df6 = pd.DataFrame(result)

print(final_df6)

               ocf         capex           fcf  fcf_ps  date
0    -5.975420e+11 -6.314900e+10 -6.606910e+11 -107.70  Q324
1    -2.494454e+12  2.168890e+11 -2.277565e+12 -216.47  Q324
2     3.484219e+12 -1.144600e+10  3.472773e+12  231.28  Q324
3     7.102710e+11 -8.500000e+09  7.017710e+11   19.96  Q324
4     1.923893e+11  2.474070e+08  1.926367e+11   10.64  Q324
...            ...           ...           ...     ...   ...
1477  6.815105e+12 -3.456100e+10  6.780544e+12  591.02  Q115
1478  4.347200e+10 -5.848000e+09  3.762400e+10    8.73  Q115
1479  9.455293e+12 -4.642000e+10  9.408873e+12  390.61  Q115
1480  8.812998e+10 -9.431560e+08  8.718682e+10    8.86  Q115
1481 -2.923840e+11 -1.226400e+10 -3.046480e+11  -58.46  Q115

[1482 rows x 5 columns]

In [85]:
final_df6 = final_df6.drop(columns=['ocf','capex','date'])

In [86]:
df7 = pd.read_csv('fnb_data_cash flow.csv')

In [87]:
col_index = df7.columns.get_loc('Q115') + 1
df7 = df7.iloc[:, :col_index]
df7.drop('Unnamed: 0', axis=1, inplace=True)

In [88]:
features = [
    'ocf','capex','fcf','fcf_ps'
]

result = []
for col in df7.columns:
    for start in range(0, len(df7), 4):
        if start + 4 <= len(df7):
            row = {feature: df7[col].iloc[start + i] for i, feature in enumerate(features)}
            row['date'] = col
            result.append(row)

# Mengubah hasil menjadi DataFrame baru
final_df7 = pd.DataFrame(result)

print(final_df7)

              ocf         capex           fcf  fcf_ps  date
0    1.018950e+11 -1.103650e+11 -8.470000e+09  -14.36  Q324
1    1.184130e+11  1.223700e+10  1.306500e+11   14.03  Q324
2    1.078277e+09 -2.226139e+08  8.556627e+08    0.39  Q324
3    1.759462e+10  1.640065e+10  3.399527e+10    0.73  Q324
4    5.619600e+10 -1.530300e+10  4.089300e+10    9.09  Q324
..            ...           ...           ...     ...   ...
814  1.421184e+10 -8.305036e+09  5.906803e+09    8.55  Q115
815  6.734440e+09 -3.756599e+10 -3.083155e+10  -23.54  Q115
816  1.435240e+11 -1.923290e+11 -4.880500e+10   -9.88  Q115
817  2.032402e+11 -6.657817e+10  1.366620e+11   47.31  Q115
818  1.056407e+12 -2.688850e+11  7.875220e+11  103.21  Q115

[819 rows x 5 columns]

In [89]:
final_df7

              ocf         capex           fcf  fcf_ps  date
0    1.018950e+11 -1.103650e+11 -8.470000e+09  -14.36  Q324
1    1.184130e+11  1.223700e+10  1.306500e+11   14.03  Q324
2    1.078277e+09 -2.226139e+08  8.556627e+08    0.39  Q324
3    1.759462e+10  1.640065e+10  3.399527e+10    0.73  Q324
4    5.619600e+10 -1.530300e+10  4.089300e+10    9.09  Q324
..            ...           ...           ...     ...   ...
814  1.421184e+10 -8.305036e+09  5.906803e+09    8.55  Q115
815  6.734440e+09 -3.756599e+10 -3.083155e+10  -23.54  Q115
816  1.435240e+11 -1.923290e+11 -4.880500e+10   -9.88  Q115
817  2.032402e+11 -6.657817e+10  1.366620e+11   47.31  Q115
818  1.056407e+12 -2.688850e+11  7.875220e+11  103.21  Q115

[819 rows x 5 columns]

In [90]:
final_df7 = final_df7.drop(columns=['ocf','capex','date'])

In [91]:
financial_final = pd.concat([final_df2, final_df4, final_df6], axis=1)
fnb_final = pd.concat([final_df3, final_df5, final_df7], axis=1)

In [92]:
financial_final.T

,0,1,2,3,4,5,6,7,8,9,...,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481
eps,6.74,41.55,20.59,0.49,0.28,165.71,4.87,68.66,5.64,34.72,...,-96633000000.0,71.66,-5.58,1.76,53.98,32.45,0.75,24.41,1.88,19.36
per,620.18,23.23,27.68,124.49,2875.0,41.79,146.82,27.38,40.78,33.7,...,-0.0,71.52,-2.15,126.7,42.72,43.14,1086.67,58.38,123.94,58.88
ebitda,65990000000.0,519938000000.0,509979000000.0,45101000000.0,14635646000.0,21848948000000.0,26974336113.0,2322498000000.0,694936000000.0,1714482000000.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
roa,0.18,0.21,0.29,0.14,0.02,0.67,0.2,0.49,0.23,0.49,...,-0.78,0.35,-0.75,0.1,0.61,0.32,0.05,0.35,0.29,0.56
roe,1.13,2.72,2.5,0.36,0.08,5.68,0.52,3.32,1.42,2.98,...,-7.85,2.05,-10.42,0.85,5.19,2.43,0.27,2.72,1.69,2.51
date,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,...,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115
emiten_code,BINA,BJBR,BJTM,BKSW,BMAS,BMRI,BNBA,BNGA,BNII,BNLI,...,BCIC,BDMN,BEKS,MCOR,MEGA,NISP,NOBU,PNBN,PNBS,SDRA
pbv,6.99,0.63,0.69,0.45,2.15,2.38,0.76,0.91,0.58,1.0,...,0.0,1.47,0.22,1.07,2.22,1.05,2.96,1.59,2.1,1.48
bvps,598.1,1528.97,822.24,135.4,374.51,2915.56,939.14,2069.71,395.86,1164.69,...,1230553000000.0,3495.73,53.56,208.0,1040.34,1336.26,274.88,896.42,111.07,771.51
fcf,-660691000000.0,-2277565000000.0,3472773000000.0,701771000000.0,192636746000.0,-42193515000000.0,-257767931609.0,6615516000000.0,1608675000000.0,-885445000000.0,...,-1541669000000.0,280161000000.0,-375425000000.0,-240473000000.0,-3088769000000.0,6780544000000.0,37624000000.0,9408873000000.0,87186824000.0,-304648000000.0
fcf_ps,-107.7,-216.47,231.28,19.96,10.64,-452.07,-76.08,263.12,21.11,-24.47,...,-1541669000000.0,29.23,-34.91,-40.61,-443.55,591.02,8.73,390.61,8.86,-58.46

In [93]:
fnb_final.T

,0,1,2,3,4,5,6,7,8,9,...,809,810,811,812,813,814,815,816,817,818
eps,196.76,1.98,-6.72,0.22,4.33,124.81,35.62,395.45,-0.11,558.8,...,50.94,304.93,NaN,13.26,6.57,5.67,39.55,18.39,51.5,208.61
per,51.2,66.16,-2.38,18.18,53.58,16.75,69.06,31.17,-454.55,12.62,...,192.38,94.78,NaN,92.01,147.64,56.44,77.24,35.07,77.13,190.07
ebitda,149838000000.0,55190000000.0,-17018172514.0,8404273749.0,77194000000.0,100377149296.0,37850613000.0,3548895000000.0,-2710291457.0,5438064000000.0,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
roa,4.69,0.95,-1.58,0.25,0.53,3.32,2.58,3.71,-1.88,2.51,...,5.25,2.59,NaN,2.47,0.96,1.15,2.91,1.21,4.72,10.77
roe,5.58,1.79,-4.94,0.93,1.3,4.12,3.53,9.99,-2.13,7.54,...,16.24,6.37,NaN,6.53,2.31,2.49,6.06,3.58,6.19,24.89
date,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,Q324,...,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115,Q115
emiten_code,ADES,AISA,ALTO,BTEK,BUDI,CEKA,DLTA,ICBP,IIKP,INDF,...,MLBI,MYOR,PSDN,ROTI,SKBM,SKLT,STTP,TBLA,ULTJ,UNVR
pbv,2.86,1.18,0.12,0.17,0.7,0.69,2.44,3.11,9.38,0.95,...,31.24,6.04,NaN,6.01,3.42,1.41,4.69,1.26,4.77,47.31
bvps,3525.89,110.77,136.07,23.56,333.41,3026.64,1008.43,3957.33,5.33,7410.02,...,313.69,4788.14,NaN,202.94,283.98,227.58,652.08,513.49,832.15,838.14
fcf,-8470000000.0,130650000000.0,855662730.0,33995272251.0,40893000000.0,10244458109.0,26311613000.0,895979000000.0,-16248634.0,2816039000000.0,...,185075000000.0,977138666148.0,NaN,108714592929.0,-23486583063.0,5906802566.0,-30831552411.0,-48805000000.0,136661998425.0,787522000000.0
fcf_ps,-14.36,14.03,0.39,0.73,9.09,17.22,32.86,76.83,-0.0,320.72,...,87.84,1092.57,NaN,21.48,-25.08,8.55,-23.54,-9.88,47.31,103.21

In [94]:
macro = {
    'year' : [2015,2016,2017,2018,2019,2020,2021,2022,2023,2024],
    'gdp_forecast' : [5.2,5.1,5.1,5.3,5.1,-2.2,3.7,5.2,4.9,5],
    'political_stability' : [17.1,21.4,17.1,15.6,17.5,18.4,17.9,15.5,17.5,17.1],
    'inflation_forecast' : [4,4,4,3.5,3.5,3,3,3,3,2.5]
}

In [95]:
df_mac = pd.DataFrame(macro)

In [96]:
df_mac

   year  gdp_forecast  political_stability  inflation_forecast
0  2015           5.2                 17.1                 4.0
1  2016           5.1                 21.4                 4.0
2  2017           5.1                 17.1                 4.0
3  2018           5.3                 15.6                 3.5
4  2019           5.1                 17.5                 3.5
5  2020          -2.2                 18.4                 3.0
6  2021           3.7                 17.9                 3.0
7  2022           5.2                 15.5                 3.0
8  2023           4.9                 17.5                 3.0
9  2024           5.0                 17.1                 2.5

In [97]:
financial_final["year"] = financial_final["date"].str[-2:].astype(int) + 2000

In [98]:
financial_final

,eps,per,ebitda,roa,roe,date,emiten_code,pbv,bvps,fcf,fcf_ps,year
0,6.74,620.18,6.599000e+10,0.18,1.13,Q324,BINA,6.99,598.10,-6.606910e+11,-107.70,2024
1,41.55,23.23,5.199380e+11,0.21,2.72,Q324,BJBR,0.63,1528.97,-2.277565e+12,-216.47,2024
2,20.59,27.68,5.099790e+11,0.29,2.50,Q324,BJTM,0.69,822.24,3.472773e+12,231.28,2024
3,0.49,124.49,4.510100e+10,0.14,0.36,Q324,BKSW,0.45,135.40,7.017710e+11,19.96,2024
4,0.28,2875.00,1.463565e+10,0.02,0.08,Q324,BMAS,2.15,374.51,1.926367e+11,10.64,2024
...,...,...,...,...,...,...,...,...,...,...,...,...
1477,32.45,43.14,0.000000e+00,0.32,2.43,Q115,NISP,1.05,1336.26,6.780544e+12,591.02,2015
1478,0.75,1086.67,0.000000e+00,0.05,0.27,Q115,NOBU,2.96,274.88,3.762400e+10,8.73,2015
1479,24.41,58.38,0.000000e+00,0.35,2.72,Q115,PNBN,1.59,896.42,9.408873e+12,390.61,2015
1480,1.88,123.94,0.000000e+00,0.29,1.69,Q115,PNBS,2.10,111.07,8.718682e+10,8.86,2015
1481,19.36,58.88,0.000000e+00,0.56,2.51,Q115,SDRA,1.48,771.51,-3.046480e+11,-58.46,2015

In [99]:
financial_final = financial_final.merge(df_mac, on="year", how="left")

In [100]:
financial_final

,eps,per,ebitda,roa,roe,date,emiten_code,pbv,bvps,fcf,fcf_ps,year,gdp_forecast,political_stability,inflation_forecast
0,6.74,620.18,6.599000e+10,0.18,1.13,Q324,BINA,6.99,598.10,-6.606910e+11,-107.70,2024,5.0,17.1,2.5
1,41.55,23.23,5.199380e+11,0.21,2.72,Q324,BJBR,0.63,1528.97,-2.277565e+12,-216.47,2024,5.0,17.1,2.5
2,20.59,27.68,5.099790e+11,0.29,2.50,Q324,BJTM,0.69,822.24,3.472773e+12,231.28,2024,5.0,17.1,2.5
3,0.49,124.49,4.510100e+10,0.14,0.36,Q324,BKSW,0.45,135.40,7.017710e+11,19.96,2024,5.0,17.1,2.5
4,0.28,2875.00,1.463565e+10,0.02,0.08,Q324,BMAS,2.15,374.51,1.926367e+11,10.64,2024,5.0,17.1,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,32.45,43.14,0.000000e+00,0.32,2.43,Q115,NISP,1.05,1336.26,6.780544e+12,591.02,2015,5.2,17.1,4.0
1478,0.75,1086.67,0.000000e+00,0.05,0.27,Q115,NOBU,2.96,274.88,3.762400e+10,8.73,2015,5.2,17.1,4.0
1479,24.41,58.38,0.000000e+00,0.35,2.72,Q115,PNBN,1.59,896.42,9.408873e+12,390.61,2015,5.2,17.1,4.0
1480,1.88,123.94,0.000000e+00,0.29,1.69,Q115,PNBS,2.10,111.07,8.718682e+10,8.86,2015,5.2,17.1,4.0
1481,19.36,58.88,0.000000e+00,0.56,2.51,Q115,SDRA,1.48,771.51,-3.046480e+11,-58.46,2015,5.2,17.1,4.0

In [101]:
fnb_final["year"] = fnb_final["date"].str[-2:].astype(int) + 2000
fnb_final = fnb_final.merge(df_mac, on="year", how="left")

In [102]:
fnb_final

,eps,per,ebitda,roa,roe,date,emiten_code,pbv,bvps,fcf,fcf_ps,year,gdp_forecast,political_stability,inflation_forecast
0,196.76,51.20,1.498380e+11,4.69,5.58,Q324,ADES,2.86,3525.89,-8.470000e+09,-14.36,2024,5.0,17.1,2.5
1,1.98,66.16,5.519000e+10,0.95,1.79,Q324,AISA,1.18,110.77,1.306500e+11,14.03,2024,5.0,17.1,2.5
2,-6.72,-2.38,-1.701817e+10,-1.58,-4.94,Q324,ALTO,0.12,136.07,8.556627e+08,0.39,2024,5.0,17.1,2.5
3,0.22,18.18,8.404274e+09,0.25,0.93,Q324,BTEK,0.17,23.56,3.399527e+10,0.73,2024,5.0,17.1,2.5
4,4.33,53.58,7.719400e+10,0.53,1.30,Q324,BUDI,0.70,333.41,4.089300e+10,9.09,2024,5.0,17.1,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,5.67,56.44,0.000000e+00,1.15,2.49,Q115,SKLT,1.41,227.58,5.906803e+09,8.55,2015,5.2,17.1,4.0
815,39.55,77.24,0.000000e+00,2.91,6.06,Q115,STTP,4.69,652.08,-3.083155e+10,-23.54,2015,5.2,17.1,4.0
816,18.39,35.07,0.000000e+00,1.21,3.58,Q115,TBLA,1.26,513.49,-4.880500e+10,-9.88,2015,5.2,17.1,4.0
817,51.50,77.13,0.000000e+00,4.72,6.19,Q115,ULTJ,4.77,832.15,1.366620e+11,47.31,2015,5.2,17.1,4.0
818,208.61,190.07,0.000000e+00,10.77,24.89,Q115,UNVR,47.31,838.14,7.875220e+11,103.21,2015,5.2,17.1,4.0

In [104]:
fnb_final = fnb_final[['emiten_code','year','date','eps','per','pbv','bvps','ebitda','roa','roe',
                      'fcf','fcf_ps','gdp_forecast','political_stability','inflation_forecast']]
fnb_final = fnb_final.sort_values(by=["emiten_code", "year"], ascending=[True, False]).reset_index(drop=True)

In [105]:
fnb_final

,emiten_code,year,date,eps,per,pbv,bvps,ebitda,roa,roe,fcf,fcf_ps,gdp_forecast,political_stability,inflation_forecast
0,ADES,2024,Q324,196.76,51.20,2.86,3525.89,1.498380e+11,4.69,5.58,-8.470000e+09,-14.36,5.0,17.1,2.5
1,ADES,2024,Q224,173.98,60.78,3.18,3329.13,1.320190e+11,4.45,5.23,3.963500e+10,67.19,5.0,17.1,2.5
2,ADES,2024,Q124,222.76,40.85,2.88,3155.15,1.662250e+11,5.81,7.06,7.798300e+10,132.20,5.0,17.1,2.5
3,ADES,2023,Q423,176.16,54.92,3.30,2932.39,1.398630e+11,4.98,6.01,1.156430e+11,196.04,4.9,17.5,3.0
4,ADES,2023,Q323,180.55,58.85,3.85,2757.63,1.372790e+11,5.49,6.55,1.074140e+11,182.09,4.9,17.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,UNVR,2016,Q116,205.77,208.61,51.20,838.45,0.000000e+00,9.43,24.54,1.053940e+12,138.13,5.1,21.4,4.0
815,UNVR,2015,Q415,218.69,169.19,58.48,632.68,0.000000e+00,10.61,34.57,2.200957e+12,288.46,5.2,17.1,4.0
816,UNVR,2015,Q315,164.16,231.48,49.88,761.78,0.000000e+00,7.84,21.55,6.868200e+11,90.02,5.2,17.1,4.0
817,UNVR,2015,Q215,175.48,225.10,66.10,597.62,0.000000e+00,8.12,29.36,1.151308e+12,150.89,5.2,17.1,4.0
818,UNVR,2015,Q115,208.61,190.07,47.31,838.14,0.000000e+00,10.77,24.89,7.875220e+11,103.21,5.2,17.1,4.0

In [106]:
financial_final = financial_final[['emiten_code','year','date','eps','per','pbv','bvps','ebitda','roa','roe',
                      'fcf','fcf_ps','gdp_forecast','political_stability','inflation_forecast']]
financial_final = financial_final.sort_values(by=["emiten_code", "year"], ascending=[True, False]).reset_index(drop=True)

In [107]:
financial_final.to_csv("clean_financial_dataset.csv", index=False)

In [108]:
fnb_final.to_csv("clean_fnb_dataset.csv", index=False)